# Generated by Django 4.0.4 on 2022-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrainement',
            name='Dates',
            field=models.DateField(),
        ),
    ]
